proxy:
  name: proxy
  # /* represents all interfaces below proxy /, no distinction between /* and /**
  servletUrl: /*
  targetUrl: http://jetbrains.meethigher.top
  log:
    enable: true
    # Configure the agent’s log format. The options are remoteAddr、remotePort、userAgent、method、source、target
    logFormat: "{remoteAddr} {remotePort} {userAgent} {method} uri: {source} -- {target}"
  corsControl:
    enable: true
    allowCORS: false
server:
  port: 8086