logging:
  config: classpath:log/logback.xml
  file:
    path: logs
server:
  port: 8080
proxy:
  servlets:
    - name: bing
      # /* represents all interfaces below proxy /, no distinction between /* and /**
      servletUrl: /*
      targetUrl: https://meethigher.top
      # if true, carry header x-forwarded-for
      xForwardedFor: true
      # if true, reserve proxy server host
      preserveHost: true
      # if true, reserve origin header cookies
      preserveCookies: true
      # if true, when requesting a redirect URL, the URL returns the result after the redirect
      followRedirects: true
      log:
        enable: true
        # configure the agent’s log format. the options are remoteAddr、remotePort、userAgent、method、source、target、consumedMills
        logFormat: "{remoteAddr} {method} uri: {source} --> {target} consumed {consumedMills} ms"
      corsControl:
        # true means that the cors of all requests is managed by http-proxy-boot;
        # false means that the cors of all requests is managed by the source service.
        enable: false
        # true means that the cors of all requests is allowed when enable=true
        # false means that the cors of all requests is not allowed then enable=true
        allowCORS: true
    - name: jetbrains
      servletUrl: /tes1t/*
      targetUrl: http://jetbrains.meethigher.top